// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orion.Context;

#nullable disable

namespace Orion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240329133221_OrionUpdate")]
    partial class OrionUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("CustomerEvent", b =>
                {
                    b.Property<int>("CustomersId")
                        .HasColumnType("integer");

                    b.Property<int>("EventsId")
                        .HasColumnType("integer");

                    b.HasKey("CustomersId", "EventsId");

                    b.HasIndex("EventsId");

                    b.ToTable("CustomerEvent");
                });

            modelBuilder.Entity("Orion.Models.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvertisementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("Orion.Models.Booth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("BoothCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("BoothNumber")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("Booths");
                });

            modelBuilder.Entity("Orion.Models.Craft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("CraftItem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CraftName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Crafts");
                });

            modelBuilder.Entity("Orion.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<int>("DonationId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<int>("WebsiteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DonationId")
                        .IsUnique();

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("WebsiteId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Orion.Models.CustomerAdvertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvertisementId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAdvertisements");
                });

            modelBuilder.Entity("Orion.Models.CustomerProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("CustomerProducts");
                });

            modelBuilder.Entity("Orion.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceDateOfPurchase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaintenancePrice")
                        .HasColumnType("integer");

                    b.Property<int>("OfficeWorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId")
                        .IsUnique();

                    b.HasIndex("OfficeWorkerId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Orion.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("DonationMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DonationQuantity")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DonationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DonationType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("Orion.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EmployeeDateOfJoin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeInsurance")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeePension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeQualifications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeSalary")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Employee");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Orion.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("BoothId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventPlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Orion.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("OfficeWorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OfficeWorkerId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Orion.Models.Freelancer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("Earnings")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<int>("OrphanageId")
                        .HasColumnType("integer");

                    b.Property<int>("OrphansNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrphanageId");

                    b.ToTable("Freelancers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Freelancer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Orion.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialPrice")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Orion.Models.MaterialVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("VendorId");

                    b.ToTable("MaterialVendors");
                });

            modelBuilder.Entity("Orion.Models.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<int>("CraftId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MentorArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<int>("OrphanNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<int>("VisitNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CraftId");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("Orion.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("OrderAmount")
                        .HasColumnType("integer");

                    b.Property<string>("OrderComments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderPrice")
                        .HasColumnType("integer");

                    b.Property<int>("OrderQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Orders");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Order");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Orion.Models.Orphanage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("OrphanageAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrphanageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrphanageNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orphanages");
                });

            modelBuilder.Entity("Orion.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentAmount")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Orion.Models.PreCommunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("PreCommunities");
                });

            modelBuilder.Entity("Orion.Models.PremiumUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Fees")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("PreCommunityId")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PreCommunityId");

                    b.ToTable("PremiumUsers");
                });

            modelBuilder.Entity("Orion.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("Above12Id")
                        .HasColumnType("integer");

                    b.Property<string>("Customization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("integer");

                    b.Property<string>("ProductSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reviews")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Above12Id");

                    b.HasIndex("EventId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Orion.Models.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DonationId")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("SponsorAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SponsorEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SponsorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SponsorPhone")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DonationId");

                    b.HasIndex("EventId");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("Orion.Models.SponsorAdvertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvertisementId")
                        .HasColumnType("integer");

                    b.Property<int>("SponsorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.HasIndex("SponsorId");

                    b.ToTable("SponsorAdvertisements");
                });

            modelBuilder.Entity("Orion.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("VendorAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Orion.Models.Website", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int>("OfficeWorkerId")
                        .HasColumnType("integer");

                    b.Property<string>("WebsiteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OfficeWorkerId");

                    b.ToTable("Websites");
                });

            modelBuilder.Entity("Orion.Models.Admin", b =>
                {
                    b.HasBaseType("Orion.Models.Employee");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<int>("WebsiteId")
                        .HasColumnType("integer");

                    b.HasIndex("WebsiteId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Orion.Models.Delivery", b =>
                {
                    b.HasBaseType("Orion.Models.Employee");

                    b.Property<string>("DeliveryLicense")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryShift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VechileNumber")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Delivery");
                });

            modelBuilder.Entity("Orion.Models.OfficeWorker", b =>
                {
                    b.HasBaseType("Orion.Models.Employee");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("OfficeWorkerDepartment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Employees", t =>
                        {
                            t.Property("DeviceId")
                                .HasColumnName("OfficeWorker_DeviceId");
                        });

                    b.HasDiscriminator().HasValue("OfficeWorker");
                });

            modelBuilder.Entity("Orion.Models.Supervisor", b =>
                {
                    b.HasBaseType("Orion.Models.Employee");

                    b.HasDiscriminator().HasValue("Supervisor");
                });

            modelBuilder.Entity("Orion.Models.Above12", b =>
                {
                    b.HasBaseType("Orion.Models.Freelancer");

                    b.HasDiscriminator().HasValue("Above12");
                });

            modelBuilder.Entity("Orion.Models.Under12", b =>
                {
                    b.HasBaseType("Orion.Models.Freelancer");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("integer");

                    b.HasIndex("SupervisorId");

                    b.HasDiscriminator().HasValue("Under12");
                });

            modelBuilder.Entity("Orion.Models.BoothOrder", b =>
                {
                    b.HasBaseType("Orion.Models.Order");

                    b.Property<int>("BoothId")
                        .HasColumnType("integer");

                    b.HasIndex("BoothId");

                    b.HasDiscriminator().HasValue("BoothOrder");
                });

            modelBuilder.Entity("Orion.Models.DeliveryOrder", b =>
                {
                    b.HasBaseType("Orion.Models.Order");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<double>("ShippingFees")
                        .HasColumnType("double precision");

                    b.HasIndex("DeliveryId");

                    b.HasDiscriminator().HasValue("DeliveryOrder");
                });

            modelBuilder.Entity("CustomerEvent", b =>
                {
                    b.HasOne("Orion.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orion.Models.Booth", b =>
                {
                    b.HasOne("Orion.Models.Event", "Event")
                        .WithOne("Booth")
                        .HasForeignKey("Orion.Models.Booth", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Orion.Models.Customer", b =>
                {
                    b.HasOne("Orion.Models.Donation", "Donation")
                        .WithOne("Customer")
                        .HasForeignKey("Orion.Models.Customer", "DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Models.Payment", "Payment")
                        .WithOne("Customer")
                        .HasForeignKey("Orion.Models.Customer", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Models.Website", "Website")
                        .WithMany("Customers")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Payment");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Orion.Models.CustomerAdvertisement", b =>
                {
                    b.HasOne("Orion.Models.Advertisement", "Advertisement")
                        .WithMany("CustomerAdvertisements")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Models.Customer", "Customer")
                        .WithMany("CustomerAdvertisements")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Orion.Models.CustomerProduct", b =>
                {
                    b.HasOne("Orion.Models.Customer", "Customer")
                        .WithMany("CustomerProducts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Models.Product", "Product")
                        .WithMany("CustomerProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Orion.Models.Device", b =>
                {
                    b.HasOne("Orion.Models.Admin", "Admin")
                        .WithOne("Device")
                        .HasForeignKey("Orion.Models.Device", "AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Models.OfficeWorker", "OfficeWorker")
                        .WithOne("Device")
                        .HasForeignKey("Orion.Models.Device", "OfficeWorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("OfficeWorker");
                });

            modelBuilder.Entity("Orion.Models.Feedback", b =>
                {
                    b.HasOne("Orion.Models.Admin", "Admin")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Models.Customer", "Customer")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Models.OfficeWorker", "OfficeWorker")
                        .WithMany("Feedbacks")
                        .HasForeignKey("OfficeWorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("OfficeWorker");
                });

            modelBuilder.Entity("Orion.Models.Freelancer", b =>
                {
                    b.HasOne("Orion.Models.Orphanage", "Orphanage")
                        .WithMany("Freelancers")
                        .HasForeignKey("OrphanageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orphanage");
                });

            modelBuilder.Entity("Orion.Models.MaterialVendor", b =>
                {
                    b.HasOne("Orion.Models.Material", "Material")
                        .WithMany("MaterialVendors")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Models.Vendor", "Vendor")
                        .WithMany("MaterialVendors")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Orion.Models.Mentor", b =>
                {
                    b.HasOne("Orion.Models.Craft", "Craft")
                        .WithMany("Mentors")
                        .HasForeignKey("CraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Craft");
                });

            modelBuilder.Entity("Orion.Models.Order", b =>
                {
                    b.HasOne("Orion.Models.Customer", "Customer")
                        .WithOne("Order")
                        .HasForeignKey("Orion.Models.Order", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Orion.Models.PremiumUser", b =>
                {
                    b.HasOne("Orion.Models.PreCommunity", "PreCommunity")
                        .WithMany("PremiumUsers")
                        .HasForeignKey("PreCommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreCommunity");
                });

            modelBuilder.Entity("Orion.Models.Product", b =>
                {
                    b.HasOne("Orion.Models.Above12", "Above12")
                        .WithMany("Products")
                        .HasForeignKey("Above12Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Models.Event", "Event")
                        .WithMany("Products")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Models.Supervisor", "Supervisor")
                        .WithMany("Products")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Above12");

                    b.Navigation("Event");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Orion.Models.Sponsor", b =>
                {
                    b.HasOne("Orion.Models.Donation", "Donation")
                        .WithMany("Sponsors")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Models.Event", "Event")
                        .WithMany("Sponsors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Orion.Models.SponsorAdvertisement", b =>
                {
                    b.HasOne("Orion.Models.Advertisement", "Advertisement")
                        .WithMany("SponsorAdvertisements")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.Models.Sponsor", "Sponsor")
                        .WithMany("SponsorAdvertisements")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("Orion.Models.Website", b =>
                {
                    b.HasOne("Orion.Models.OfficeWorker", "OfficeWorker")
                        .WithMany("Websites")
                        .HasForeignKey("OfficeWorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficeWorker");
                });

            modelBuilder.Entity("Orion.Models.Admin", b =>
                {
                    b.HasOne("Orion.Models.Website", "Website")
                        .WithOne("Admin")
                        .HasForeignKey("Orion.Models.Admin", "WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Orion.Models.Under12", b =>
                {
                    b.HasOne("Orion.Models.Supervisor", "Supervisor")
                        .WithMany("Under12s")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Orion.Models.BoothOrder", b =>
                {
                    b.HasOne("Orion.Models.Booth", "Booth")
                        .WithMany("BoothOrders")
                        .HasForeignKey("BoothId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booth");
                });

            modelBuilder.Entity("Orion.Models.DeliveryOrder", b =>
                {
                    b.HasOne("Orion.Models.Delivery", "Delivery")
                        .WithMany("DeliveryOrders")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("Orion.Models.Advertisement", b =>
                {
                    b.Navigation("CustomerAdvertisements");

                    b.Navigation("SponsorAdvertisements");
                });

            modelBuilder.Entity("Orion.Models.Booth", b =>
                {
                    b.Navigation("BoothOrders");
                });

            modelBuilder.Entity("Orion.Models.Craft", b =>
                {
                    b.Navigation("Mentors");
                });

            modelBuilder.Entity("Orion.Models.Customer", b =>
                {
                    b.Navigation("CustomerAdvertisements");

                    b.Navigation("CustomerProducts");

                    b.Navigation("Feedbacks");

                    b.Navigation("Order")
                        .IsRequired();
                });

            modelBuilder.Entity("Orion.Models.Donation", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Sponsors");
                });

            modelBuilder.Entity("Orion.Models.Event", b =>
                {
                    b.Navigation("Booth")
                        .IsRequired();

                    b.Navigation("Products");

                    b.Navigation("Sponsors");
                });

            modelBuilder.Entity("Orion.Models.Material", b =>
                {
                    b.Navigation("MaterialVendors");
                });

            modelBuilder.Entity("Orion.Models.Orphanage", b =>
                {
                    b.Navigation("Freelancers");
                });

            modelBuilder.Entity("Orion.Models.Payment", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();
                });

            modelBuilder.Entity("Orion.Models.PreCommunity", b =>
                {
                    b.Navigation("PremiumUsers");
                });

            modelBuilder.Entity("Orion.Models.Product", b =>
                {
                    b.Navigation("CustomerProducts");
                });

            modelBuilder.Entity("Orion.Models.Sponsor", b =>
                {
                    b.Navigation("SponsorAdvertisements");
                });

            modelBuilder.Entity("Orion.Models.Vendor", b =>
                {
                    b.Navigation("MaterialVendors");
                });

            modelBuilder.Entity("Orion.Models.Website", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Orion.Models.Admin", b =>
                {
                    b.Navigation("Device")
                        .IsRequired();

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Orion.Models.Delivery", b =>
                {
                    b.Navigation("DeliveryOrders");
                });

            modelBuilder.Entity("Orion.Models.OfficeWorker", b =>
                {
                    b.Navigation("Device")
                        .IsRequired();

                    b.Navigation("Feedbacks");

                    b.Navigation("Websites");
                });

            modelBuilder.Entity("Orion.Models.Supervisor", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Under12s");
                });

            modelBuilder.Entity("Orion.Models.Above12", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
